# Generated by Django 3.0b1 on 2020-02-28 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditorium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriumreservation',
            name='requestor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auditoriumreservation_requestor', to=settings.AUTH_USER_MODEL),
        ),
    ]
