# Generated by Django 3.0b1 on 2020-03-15 18:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('year_of_passing', models.CharField(max_length=5)),
                ('date_of_birth', models.DateTimeField()),
                ('martial_status', models.TextField()),
                ('profession', models.TextField()),
                ('address', models.TextField()),
                ('graduation', models.TextField()),
                ('graduation1', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('requestor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alumni_requestor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
