# Generated by Django 3.0b1 on 2020-03-05 11:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DaycareReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('requestor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daycarereservation_requestor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
